<?php
/**
 * @file
 * Provides integration between Colorbox and file fields.
 */

/**
 * Implements hook_theme().
 */
function colorbox_file_theme() {
  return array(
    'colorbox_file' => array(
      'variables' => array(
        'item' => array(),
        'entity_id' => NULL,
        'field' => array(),
        'display_settings' => array(),
        'langcode' => NULL,
        'path' => NULL,
        'title' => NULL,
        'colorbox_file_caption' => NULL, //added for chapter 7
      ),
      'path' => drupal_get_path('module', 'colorbox_file'),
      'file' => 'colorbox_file.theme.inc',
    ),
  );
}

/**
 * Implements hook_menu().
 */
function colorbox_file_menu() {
  $items['colorbox_file/%file/%/%'] = array(
    'title' => 'Colorbox',
    'page callback' => 'colorbox_file_callback',
    'page arguments' => array(1, 2, 3),
    'access callback' => 'file_entity_access',
    'access arguments' => array('view'),
    'type' => MENU_CALLBACK,
    'file' => 'colorbox_file.pages.inc',
  );
  return $items;
}

/**
 * Implements hook_field_formatter_info().
 */
function colorbox_file_field_formatter_info() {
  return array(
    'colorbox_file' => array(
      'label' => t('Colorbox file'),
      'field types' => array('media', 'file', 'image'),
      'settings' => array(
        'file_view_mode' => 'smalll',
        'colorbox_view_mode' => 'large',
        'dimensions' => '500x400',
        'colorbox_gallery' => 'post',
        'colorbox_gallery_custom' => '',
        'colorbox_caption' => 'title',//added for chapter 7
      ),
    ),
  );
}

/**
 * Implements hook_field_formatter_settings_form().
 */
function colorbox_file_field_formatter_settings_form($field, $instance, $view_mode, $form, &$form_state) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $element = array();

  if ($display['type'] == 'colorbox_file') {
    $entity_info = entity_get_info('file');
    $options = array('default' => t('Default'));
    foreach ($entity_info['view modes'] as $file_view_mode => $file_view_mode_info) {
      $options[$file_view_mode] = $file_view_mode_info['label'];
    }

    $element['file_view_mode'] = array(
      '#title' => t('File view mode'),
      '#type' => 'select',
      '#default_value' => $settings['file_view_mode'],
      '#options' => $options,
    );
    $element['colorbox_view_mode'] = array(
      '#title' => t('Colorbox view mode'),
      '#type' => 'select',
      '#default_value' => $settings['colorbox_view_mode'],
      '#options' => $options,
    );
    $element['dimensions'] = array(
      '#title' => t('Dimensions'),
      '#type' => 'textfield',
      '#default_value' => $settings['dimensions'],
      '#size' => 10,
    );
    $gallery = array(
      'post' => t('Per post gallery'),
      'page' => t('Per page gallery'),
      'field_post' => t('Per field in post gallery'),
      'field_page' => t('Per field in page gallery'),
      'custom' => t('Custom'),
      'none' => t('No gallery'),
    );
    $element['colorbox_gallery'] = array(
      '#title' => t('Gallery (image grouping)'),
      '#type' => 'select',
      '#default_value' => $settings['colorbox_gallery'],
      '#options' => $gallery,
      '#description' => t('How Colorbox should group the image galleries.'),
    );
    $element['colorbox_gallery_custom'] = array(
      '#title' => t('Custom gallery'),
      '#type' => 'machine_name',
      '#maxlength' => 32,
      '#default_value' => $settings['colorbox_gallery_custom'],
      '#description' => t('All images on a page with the same gallery value (rel attribute) will be grouped together. It must only contain lowercase letters, numbers, and underscores.'),
      '#required' => FALSE,
      '#machine_name' => array(
        'exists' => 'colorbox_gallery_exists',
        'error' => t('The custom gallery field must only contain lowercase letters, numbers, and underscores.'),
      ),
      '#states' => array(
        'visible' => array(
          ':input[name$="[settings_edit_form][settings][colorbox_gallery]"]' => array('value' => 'custom'),
        ),
      ),
    );
    //added the following for chapter 7
    $caption = array(
      'title' => t('Title text'),
      'mediafield' => t('File Type text field'),
      'none' => t('None'),
    );
    $element['colorbox_caption'] = array(
      '#title' => t('Caption'),
      '#type' => 'select',
      '#default_value' => 'title',
      '#options' => $caption,
      '#description' => t('Title will use the label of your Media field <br/>and File Type text field will use the value <br/>of a specified text field for the file type being displayed.'),
    );
  }

  return $element;
}

/**
 * Implements hook_field_formatter_settings_summary().
 */
function colorbox_file_field_formatter_settings_summary($field, $instance, $view_mode) {
  $display = $instance['display'][$view_mode];
  $settings = $display['settings'];
  $summary = array();

  if ($display['type'] == 'colorbox_file') {
    $entity_info = entity_get_info('file');
    $options = array('default' => t('Default'));
    foreach ($entity_info['view modes'] as $file_view_mode => $file_view_mode_info) {
      $options[$file_view_mode] = $file_view_mode_info['label'];
    }

    if (isset($options[$settings['file_view_mode']])) {
      $summary[] = t('File view mode: @style', array('@style' => $options[$settings['file_view_mode']]));
    }
    else {
      $summary[] = t('File view mode: none');
    }

    if (isset($options[$settings['colorbox_view_mode']])) {
      $summary[] = t('Colorbox view mode: @style', array('@style' => $options[$settings['colorbox_view_mode']]));
    }
    else {
      $summary[] = t('Colorbox view mode: none');
    }

    if (isset($settings['dimensions'])) {
      $summary[] = t('Dimensions: @dimensions', array('@dimensions' => $settings['dimensions']));
    }

    $gallery = array(
      'post' => t('Per post gallery'),
      'page' => t('Per page gallery'),
      'field_post' => t('Per field in post gallery'),
      'field_page' => t('Per field in page gallery'),
      'custom' => t('Custom'),
      'none' => t('No gallery'),
    );
    if (isset($settings['colorbox_gallery'])) {
      $summary[] = t('Colorbox gallery type: @type', array('@type' => $gallery[$settings['colorbox_gallery']])) . ($settings['colorbox_gallery'] == 'custom' ? ' (' . $settings['colorbox_gallery_custom'] . ')' : '');
    }
    //added the following for chapter 7
    $caption = array(
      'title' => t('Title text'),
      'mediafield' => t('File Type text field'),
      'none' => t('None'),
    );
    if (isset($settings['colorbox_caption'])) {
      $summary[] = t('Colorbox caption: @type', array('@type' => $caption[$settings['colorbox_caption']]));
    }
  }

  return implode('<br />', $summary);
}

/**
 * Implements hook_field_formatter_view().
 */
function colorbox_file_field_formatter_view($entity_type, $entity, $field, $instances, $langcode, $items, $display) {
  $element = array();

  if ($display['type'] == 'colorbox_file') {
    list($id, $vid, $bundle) = entity_extract_ids($entity_type, $entity);
    $files = array();

    foreach ($items as $delta => $item) {
      if (isset($item['file'])) {
        $files[$item['fid']] = $item['file'];
      }
      else {
        $files[$item['fid']] = (object) $item;
      }
    }
    $build = file_view_multiple($files, $display['settings']['file_view_mode'], 0, $langcode);

    foreach (element_children($build) as $fid) {
      $colorbox_caption_var_name = 'colorbox_file_' . $build[$fid]['#bundle'] . '_caption_field_name';//added for chapter 7
      $colorbox_caption_field_name = variable_get($colorbox_caption_var_name);//added for chapter 7

      $colorbox_field_caption_value = isset($build[$fid]['#file']->{$colorbox_caption_field_name}['und'][0]) ?
        $build[$fid]['#file']->{$colorbox_caption_field_name}['und'][0]['value'] : NULL;//added for chapter 7

      $element[$fid] = array(
        '#theme' => 'colorbox_file',
        '#item' => $build[$fid]['file'],
        '#entity_id' => $id,
        '#field' => $field,
        '#display_settings' => $display['settings'],
        '#langcode' => $langcode,
        '#path' => 'colorbox_file/' . $fid . '/' . $display['settings']['colorbox_view_mode'] . '/' . $langcode,
        //chapter 7 note: this is where Media is being added as the title attribute
        '#title' => isset($instances['label']) ? $instances['label'] : NULL,
        '#colorbox_file_caption' => $colorbox_field_caption_value,//added for chapter 7
      );
    }
  }

  return $element;
}

//everything below here was added for chapter 7
/**
 * Implements hook_form_FORM_ID_alter().
 */
function colorbox_file_form_field_ui_field_edit_form_alter(&$form, &$form_state) {
  //only want this option to appear for text fields on file entities
  if ($form['#instance']['entity_type'] == 'file' && $form['#instance']['widget']['type'] == 'text_textfield') {
    $instance = $form['instance'];
    $entity_type = $instance['entity_type']['#value'];
    $entity_info = entity_get_info($entity_type);
    $bundle = $instance['bundle']['#value'];
    $bundle_label = $entity_info['bundles'][$bundle]['label'];

    // Create the fieldset tab.
    $form['colorbox_file'] = array(
      '#type'   => 'fieldset',
      '#title'  => t('Colorbox Caption Field'),
      '#description' => t('Set field to be used as the Colorbox caption.
        Note: Selecting this text field as the Colorbox caption field will replace an previously checked field for this file type.'),
      '#tree'   => TRUE,
    );

    $form['colorbox_file']['caption_field'] = array(
      '#type' => 'checkbox',
      '#title' => t('Use field as Colorbox caption'),
    );

    //check to see if the colorbox file caption field is already set,
    //and if it is set to a different field than the current one
    if (isset($current_colorbox_file_caption_field_name)
      && $current_colorbox_file_caption_field_name !== $form['#instance']['field_name']) {
      $form['colorbox_file']['override_text'] = array(
        '#markup' => t('The @bundle file type is currently using the @field field as the Colorbox caption field,
        checking it for this field will override that value.',
          array('@bundle' => $bundle_label, '@field' => $current_colorbox_file_caption_field_name)),
      );
    }

    //additional submit function to process the caption_field checkbox value
    $form['#submit'] = array_merge($form['#submit'], array('colorbox_file_form_field_ui_field_edit_form_submit'));
  }
}

/**
 * Custom submit handler for the field_ui_field_edit_form altered form.
 */
function colorbox_file_form_field_ui_field_edit_form_submit($form, &$form_state) {
  dd($form, 'colorbox_file_form_field_ui_field_edit_form_submit form');
  if ($form['colorbox_file']['caption_field']) {
    $bundle = $form['instance']['bundle']['#value'];
    variable_set('colorbox_file_' . $bundle . '_caption_field_name', $form['#field']['field_name']);
    field_flush_caches();
  }
}
