<?php

/**
 * Implements hook_preprocess_node().
 */
/*function d7dev_theme_alpha_preprocess_node(&$vars) {
  //add a prefix to first field to be part of the box
  $vars['content']['field_preptime']['#prefix'] = '<div class="time-yield-wrapper">';
  //close the box by adding a suffix to the last field to be part of the box
  $vars['content']['field_recipeyield']['#suffix'] = '</div>';
}*/